fix: Clear cache properly when .eslintrc changes
AtomLinter/linter-eslint-node pull request #33
Opened 2023-01-29 19:17 UTC by savetheclocktower

This was an oversight; file it under “how did this ever work?” Rather than iterating over keys, I was iterating over the key/value array yielded by each `Map`, so deletion had no effect, because I was asking it to delete keys that did not exist.

To verify:

1. Make sure the “Use cache” setting is enabled.
2. Trigger a linter error/warning in a file in your project.
3. Change your `.eslintrc` so that it no longer cares about that rule.
4. Go back to your file and re-save.

On `main`, the linting error/warning won't go away. On this PR branch, it will.

2023-01-30 09:12 UTC, scagood approved these changes

2023-01-30 15:53 UTC, UziTech requested changes
Can you write a test for this? It would also be better if we could get the CI to use Pulsar for the tests instead of atom.

2023-01-31 16:33 UTC, savetheclocktower commented
I can work on a test. At least some of the CI runs are failing on the setup-atom step, and I'm not sure how the ones that get past that step are doing so.

2023-01-31 17:42 UTC, savetheclocktower commented
Test added. @UziTech, I also added a snippet to the spec runner which fixes its failure to inherit `PATH` from the editor that spawned it. This might not be a problem on Windows at all, but if it's something that affects you as well, then that code block probably needs to be made more generic. Not a blocker; I imagine it doesn't affect running specs from the command line.

2023-02-02 06:38 UTC, UziTech approved these changes

2023-02-12 22:33 UTC, merged